#
# history settings
#

# Make history robust and fast.
HISTSIZE=${HISTSIZE:-50000}
SAVEHIST=${SAVEHIST:-50000}
HISTFILE=${HISTFILE:-$ZSH_DATA_DIR/.zsh_history}

setopt \
  INC_APPEND_HISTORY_TIME \
  EXTENDED_HISTORY \
  SHARE_HISTORY \
  HIST_EXPIRE_DUPS_FIRST \
  HIST_FIND_NO_DUPS \
  HIST_IGNORE_DUPS \
  HIST_IGNORE_ALL_DUPS \
  HIST_IGNORE_SPACE \
  HIST_REDUCE_BLANKS \
  HIST_SAVE_NO_DUPS \
  HIST_VERIFY
