#
# history settings
#

# Make history robust and fast.
HISTSIZE=${HISTSIZE:-20000}
SAVEHIST=${SAVEHIST:-20000}
HISTFILE=${HISTFILE:-$ZSH_DATA_DIR/.zsh_history}

setopt \
  INC_APPEND_HISTORY_TIME \
  EXTENDED_HISTORY \
  SHARE_HISTORY \
  HIST_IGNORE_DUPS \
  HIST_IGNORE_ALL_DUPS \
  HIST_REDUCE_BLANKS \
  HIST_VERIFY
